### ISSUE TITLE
Compiled version?

### ISSUE THREAD

**Issue by Darklocq** [shadeMe/Blockhead#1]
Is there a compiled version of this available somewhere? I see that Mesh Extended Swap System 2.2 includes a Blockhead v. 11 DLL (from 2016) in it, but Nexus only has v. 10.

I could theoretically compile this myself, but I'm not a "real" Windows user (Mac guy, playing Oblivion in a VM).  It's unlikely I have the necessary stuff to compile something like this in Windows.

**Comment by shadeMe** [comment]
Good point. Will add a release build.

**Comment by Darklocq** [comment]
Where would I be looking? On here somewhere, or at the Nexus page? Or a new Nexus page?

PS: Thanks for making this. I love it.

**Comment by shadeMe** [comment]
Here - https://github.com/shadeMe/Blockhead/releases
